### ISSUE TITLE
Inversion is not good

### ISSUE THREAD

**Issue by Johnson-yue** [shape-guided-diffusion/shape-guided-diffusion#1]

**Comment by Johnson-yue** [comment]
no problem!!

**Comment by Johnson-yue** [comment]
Hi, thanks for your share 

I test this edit inside and outside is good performance. But inversion maybe have a problem


I using prompt_inversion_inside and prompt_inside is below:
![image](https://user-images.githubusercontent.com/10268274/216250892-137b8271-8965-454b-ae4c-ef86738c8de7.png)

and I expect the output is the same as input_image, but it is different:
input_image :
![image](https://user-images.githubusercontent.com/10268274/216251206-ecd263dc-45ee-45a9-8278-1f756244aa3c.png)
----
mask:
![image](https://user-images.githubusercontent.com/10268274/216251276-e5a710dc-76c1-43b0-9a70-ad353df8162e.png)
-----
output_image:
![image](https://user-images.githubusercontent.com/10268274/216251338-6f12a728-8baf-4d8e-89df-6389f7949e75.png)

**Comment by g-luo** [comment]
This issue seems to be more about general DDIM inversion quality with Stable Diffusion, rather than inversion with our method. You will notice the same issues if you turn Inside-Outside Attention off and run inversion with the same hyperparameters.

To improve reconstruction quality: increase the number of steps on the scheduler (with a tradeoff with runtime), although it is upper bounded by the VQ-VAE codebook quality (i.e. text will usually be reconstructed poorly no matter the number of steps).

**Comment by Johnson-yue** [comment]
@g-luo thanks, I will check DDIM-inversion method
